name: 'Tests: node --disable-proto=throw'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '>= 12.17'
      type: minors
      command: 'NODE_OPTIONS="--disable-proto=throw" npx tape "test/**/*.js"'

  node:
    name: 'node --disable-proto=throw'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
